export const iconOutline = {
  email: 'mdi-email-outline',
  password: 'mdi-lock-outline',
  user: 'mdi-account-outline',
  plus: 'mdi-plus-outline',
  minus: 'mdi-minus',
  settings: 'mdi-cog-outline',
  signOut: 'mdi-logout',
  trash: 'mdi-delete-outline',
  close: 'mdi-close-outline',
  archive: 'mdi-archive-outline',
  edit: 'mdi-pencil-outline',
  details: 'mdi-magnify',
  ellipsis: 'mdi-ellipse-outline',
  checkCircle: 'mdi-check-circle-outline',
  exclamation: 'mdi-exclamation',
  return: 'mdi-arrow-left-top',
}
