export const iconOutline = {
  archive: 'mdi-archive-outline',
  checkCircle: 'mdi-check-circle-outline',
  close: 'mdi-close',
  close_outline: 'mdi-close-outline',
  details: 'mdi-magnify',
  'dots-horizontal': 'mdi-dots-horizontal',
  edit: 'mdi-pencil-outline',
  email: 'mdi-email-outline',
  exclamation: 'mdi-exclamation',
  expand: 'mdi-arrow-expand',
  minus: 'mdi-minus',
  password: 'mdi-lock-outline',
  plus: 'mdi-plus',
  settings: 'mdi-cog-outline',
  signOut: 'mdi-logout',
  trash: 'mdi-delete-outline',
  return: 'mdi-arrow-left-top',
  user: 'mdi-account-outline',
}
